server:
  port: 8089
  tomcat:
    uri-encoding: UTF-8
#debug: true
logging:

  level:
    com:
      rongdong: DEBUG #com.didispace包下所有class以DEBUG级别输出
#  root: WARN  #root日志以WARN级别输出  选项TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF

spring:
    output:
      ansi:
        enabled: DETECT  #多彩输出
#    messages:
#      encoding: UTF-8
    http:
      encoding:
        force: true
        charset: UTF-8
        enabled: true
    datasource:
      primary:
#          jdbc-url:  jdbc:mysql://116.62.21.28:3306/rongdong_jtx_db?characterEncoding=utf-8
#          username: root
#          password: Rongdong520@!
          jdbc-url: jdbc:mysql://120.78.226.5:3306/rongdong_jtx_db?characterEncoding=utf-8
          username: root
          password: Rongdong520@!

          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.jdbc.Driver
          filters: stat
          maxActive: 20
          initialSize: 1
          maxWait: 60000
          minIdle: 1
          timeBetweenEvictionRunsMillis: 60000
          minEvictableIdleTimeMillis: 300000
          validationQuery: select 'x'
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: true
          maxOpenPreparedStatements: 20

      second:
          jdbc-url:  jdbc:mysql://121.196.224.149:3306/rongdong_jtx_db?characterEncoding=utf-8
          username: root
          password: Rongdong520@!

      three:
          jdbc-url:  jdbc:mysql://39.108.245.58:3306/rongdong_jtx_db?characterEncoding=utf-8
          username: root
          password: Rongdong520@!

      four:
          jdbc-url:  jdbc:mysql://39.108.245.65:3306/rongdong_jtx_db?characterEncoding=utf-8
          username: root
          password: Rongdong520@!
      five:
          jdbc-url:  jdbc:mysql://47.95.144.34:3306/rongdong_jtx_db?characterEncoding=utf-8
          username: root
          password: Rongdong520@!



#mybatis:
#  mapper-locations: classpath:mapping/*.xml  #指明mapper的xml文件存放位置
#  type-aliases-package: com.rongdong.model   #指明和数据库映射的实体的所在包

#pagehelper 分页插件
#pagehelper:
#  helper-dialect: mysql
#  reasonable: true
#  support-methods-arguments: true
#  params: count=countSql